### ISSUE TITLE
Tags option does not appear correctly in intellisense

### ISSUE THREAD

**Issue by TristanColeNovus** [vers-one/dotnet-project-version-updater#13]
Using the below in VS-Code
It moans about the 'tags:' option 'Invalid action input', but still appears to run

```
- name: Update Project Revision number - Increment
  id: updateversion
  uses: vers-one/dotnet-project-version-updater@v1.6
  with:
    file: |
      "./**/*.csproj", "./**/*.vbproj", "!./**/*Test*.*", "!./**/*Backup*.*"
    tags: "csproj.Version,vbproj.Version"
    version: bump-revision
```
